<?php
/**
 * OneOfInterface
 *
 * PHP version 8.1
 *
 * @package  URLR\Model
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * URLR API Reference
 *
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul>         <li>All dates follow **ISO-8601** format</li>         <li>Most errors follow **RFC 9457** standard</li>         <li>All responses are delivered in English</li>     </ul>     All requests must include an API key generated in your workspace.     The key should be provided in the X-API-KEY HTTP header.
 *
 * The version of the OpenAPI document: 2.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace URLR\Model;

/**
 * Interface implemented by models generated from a `oneOf` schema.
 *
 * A `oneOf` schema is not represented by a value object; instead a value is one of the
 * composed member types. Classes implementing this interface only carry the metadata that
 * {@see ObjectSerializer::deserialize()} needs to resolve the concrete member type.
 *
 * @package URLR\Model
 * @author  OpenAPI Generator team
 */
interface OneOfInterface
{
    /**
     * List of the types a value of this `oneOf` schema may be. Each entry uses the same
     * notation as the values of {@see ModelInterface::openAPITypes()}.
     *
     * @return string[]
     */
    public static function getOneOfTypes(): array;

    /**
     * Name of the discriminator property used to resolve the concrete member type, or null
     * when the schema has no discriminator.
     *
     * @return string|null
     */
    public static function getOneOfDiscriminator(): ?string;

    /**
     * Mapping of discriminator values to the concrete member type. Empty when the schema has
     * no discriminator.
     *
     * @return array<string,string>
     */
    public static function getOneOfDiscriminatorMappings(): array;
}
