<?php
/**
 * StatisticGet200Response
 *
 * PHP version 8.1
 *
 * @package  URLR
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * URLR API Reference
 *
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul>         <li>All dates follow **ISO-8601** format</li>         <li>Most errors follow **RFC 9457** standard</li>         <li>All responses are delivered in English</li>     </ul>     All requests must include an API key generated in your workspace.     The key should be provided in the X-API-KEY HTTP header.
 *
 * The version of the OpenAPI document: 2.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace URLR\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use URLR\ObjectSerializer;

/**
 * StatisticGet200Response Class Doc Comment
 *
 * @package  URLR
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class StatisticGet200Response implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'statisticGet_200_response';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'linkId' => 'string',
        'visits' => 'int',
        'uniqueVisits' => 'int',
        'clicks' => 'int',
        'scans' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'linkId' => 'uuid',
        'visits' => null,
        'uniqueVisits' => null,
        'clicks' => null,
        'scans' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'linkId' => false,
        'visits' => false,
        'uniqueVisits' => false,
        'clicks' => false,
        'scans' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'linkId' => 'link_id',
        'visits' => 'visits',
        'uniqueVisits' => 'unique_visits',
        'clicks' => 'clicks',
        'scans' => 'scans'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'linkId' => 'setLinkId',
        'visits' => 'setVisits',
        'uniqueVisits' => 'setUniqueVisits',
        'clicks' => 'setClicks',
        'scans' => 'setScans'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'linkId' => 'getLinkId',
        'visits' => 'getVisits',
        'uniqueVisits' => 'getUniqueVisits',
        'clicks' => 'getClicks',
        'scans' => 'getScans'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('linkId', $data ?? [], null);
        $this->setIfExists('visits', $data ?? [], null);
        $this->setIfExists('uniqueVisits', $data ?? [], null);
        $this->setIfExists('clicks', $data ?? [], null);
        $this->setIfExists('scans', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets linkId
     *
     * @return string|null
     */
    public function getLinkId(): ?string
    {
        return $this->container['linkId'];
    }

    /**
     * Sets linkId
     *
     * @param string|null $linkId Link API ID
     *
     * @return $this
     */
    public function setLinkId(?string $linkId): static
    {
        if (is_null($linkId)) {
            throw new InvalidArgumentException('non-nullable linkId cannot be null');
        }
        $this->container['linkId'] = $linkId;

        return $this;
    }

    /**
     * Gets visits
     *
     * @return int|null
     */
    public function getVisits(): ?int
    {
        return $this->container['visits'];
    }

    /**
     * Sets visits
     *
     * @param int|null $visits Total number of visits, combining clicks and scans
     *
     * @return $this
     */
    public function setVisits(?int $visits): static
    {
        if (is_null($visits)) {
            throw new InvalidArgumentException('non-nullable visits cannot be null');
        }
        $this->container['visits'] = $visits;

        return $this;
    }

    /**
     * Gets uniqueVisits
     *
     * @return int|null
     */
    public function getUniqueVisits(): ?int
    {
        return $this->container['uniqueVisits'];
    }

    /**
     * Sets uniqueVisits
     *
     * @param int|null $uniqueVisits Number of unique visitors, combining clicks and scans
     *
     * @return $this
     */
    public function setUniqueVisits(?int $uniqueVisits): static
    {
        if (is_null($uniqueVisits)) {
            throw new InvalidArgumentException('non-nullable uniqueVisits cannot be null');
        }
        $this->container['uniqueVisits'] = $uniqueVisits;

        return $this;
    }

    /**
     * Gets clicks
     *
     * @return int|null
     */
    public function getClicks(): ?int
    {
        return $this->container['clicks'];
    }

    /**
     * Sets clicks
     *
     * @param int|null $clicks Number of clicks
     *
     * @return $this
     */
    public function setClicks(?int $clicks): static
    {
        if (is_null($clicks)) {
            throw new InvalidArgumentException('non-nullable clicks cannot be null');
        }
        $this->container['clicks'] = $clicks;

        return $this;
    }

    /**
     * Gets scans
     *
     * @return int|null
     */
    public function getScans(): ?int
    {
        return $this->container['scans'];
    }

    /**
     * Sets scans
     *
     * @param int|null $scans Number of scans
     *
     * @return $this
     */
    public function setScans(?int $scans): static
    {
        if (is_null($scans)) {
            throw new InvalidArgumentException('non-nullable scans cannot be null');
        }
        $this->container['scans'] = $scans;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


