<?php
/**
 * LinksApi
 * PHP version 8.1
 *
 * @package  URLR
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * URLR API Reference
 *
 * API powering the features of URLR.<br><br>Note that in order to facilitate integration, we provide SDKs for various languages at https://github.com/URLR.<br><br>Key API principles:<br>         <ul>         <li>All dates follow **ISO-8601** format</li>         <li>Most errors follow **RFC 9457** standard</li>         <li>All responses are delivered in English</li>     </ul>     All requests must include an API key generated in your workspace.     The key should be provided in the X-API-KEY HTTP header.
 *
 * The version of the OpenAPI document: 2.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace URLR\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use URLR\ApiException;
use URLR\Configuration;
use URLR\HeaderSelector;
use URLR\ObjectSerializer;

/**
 * LinksApi Class Doc Comment
 *
 * @package  URLR
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LinksApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var array<string,string[]> $contentTypes **/
    public const contentTypes = [
        'linkCreate' => [
            'application/json',
        ],
        'linkDelete' => [
            'application/json',
        ],
        'linkEdit' => [
            'application/json',
        ],
        'linkGet' => [
            'application/json',
        ],
        'linkList' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation linkCreate
     *
     * Create a link
     *
     * @param  \URLR\Model\LinkCreateRequest|null $linkCreateRequest Info of the link to create (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkCreate'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \URLR\Model\Link|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainCreate429Response|\URLR\Model\DomainGet500Response
     */
    public function linkCreate(
        ?\URLR\Model\LinkCreateRequest $linkCreateRequest = null,
        string $contentType = self::contentTypes['linkCreate'][0]
    ): \URLR\Model\Link|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainCreate429Response|\URLR\Model\DomainGet500Response
    {
        list($response) = $this->linkCreateWithHttpInfo($linkCreateRequest, $contentType);
        return $response;
    }

    /**
     * Operation linkCreateWithHttpInfo
     *
     * Create a link
     *
     * @param  \URLR\Model\LinkCreateRequest|null $linkCreateRequest Info of the link to create (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkCreate'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \URLR\Model\Link|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainCreate429Response|\URLR\Model\DomainGet500Response, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function linkCreateWithHttpInfo(
        ?\URLR\Model\LinkCreateRequest $linkCreateRequest = null,
        string $contentType = self::contentTypes['linkCreate'][0]
    ): array
    {
        $request = $this->linkCreateRequest($linkCreateRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\Link',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet401Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet422Response',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainCreate429Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet500Response',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\URLR\Model\Link',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\Link',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainCreate429Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation linkCreateAsync
     *
     * Create a link
     *
     * @param  \URLR\Model\LinkCreateRequest|null $linkCreateRequest Info of the link to create (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkCreate'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function linkCreateAsync(
        ?\URLR\Model\LinkCreateRequest $linkCreateRequest = null,
        string $contentType = self::contentTypes['linkCreate'][0]
    ): PromiseInterface
    {
        return $this->linkCreateAsyncWithHttpInfo($linkCreateRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation linkCreateAsyncWithHttpInfo
     *
     * Create a link
     *
     * @param  \URLR\Model\LinkCreateRequest|null $linkCreateRequest Info of the link to create (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkCreate'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function linkCreateAsyncWithHttpInfo(
        ?\URLR\Model\LinkCreateRequest $linkCreateRequest = null,
        string $contentType = self::contentTypes['linkCreate'][0]
    ): PromiseInterface
    {
        $returnType = '\URLR\Model\Link';
        $request = $this->linkCreateRequest($linkCreateRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'linkCreate'
     *
     * @param  \URLR\Model\LinkCreateRequest|null $linkCreateRequest Info of the link to create (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkCreate'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function linkCreateRequest(
        ?\URLR\Model\LinkCreateRequest $linkCreateRequest = null,
        string $contentType = self::contentTypes['linkCreate'][0]
    ): Request
    {

        $resourcePath = '/links';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($linkCreateRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($linkCreateRequest));
            } else {
                $httpBody = $linkCreateRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new \GuzzleHttp\Psr7\MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation linkDelete
     *
     * Delete a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet500Response|null
     */
    public function linkDelete(
        string $linkId,
        string $contentType = self::contentTypes['linkDelete'][0]
    ): \URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet500Response|null
    {
        list($response) = $this->linkDeleteWithHttpInfo($linkId, $contentType);
        return $response;
    }

    /**
     * Operation linkDeleteWithHttpInfo
     *
     * Delete a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: null, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function linkDeleteWithHttpInfo(
        string $linkId,
        string $contentType = self::contentTypes['linkDelete'][0]
    ): array
    {
        $request = $this->linkDeleteRequest($linkId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation linkDeleteAsync
     *
     * Delete a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function linkDeleteAsync(
        string $linkId,
        string $contentType = self::contentTypes['linkDelete'][0]
    ): PromiseInterface
    {
        return $this->linkDeleteAsyncWithHttpInfo($linkId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation linkDeleteAsyncWithHttpInfo
     *
     * Delete a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function linkDeleteAsyncWithHttpInfo(
        string $linkId,
        string $contentType = self::contentTypes['linkDelete'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->linkDeleteRequest($linkId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'linkDelete'
     *
     * @param  string $linkId Link API ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function linkDeleteRequest(
        string $linkId,
        string $contentType = self::contentTypes['linkDelete'][0]
    ): Request
    {
        // verify the required parameter 'linkId' is set
        if ($linkId === null || (is_array($linkId) && count($linkId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $linkId when calling linkDelete'
            );
        }

        $resourcePath = '/links/{link_id}';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($linkId !== null) {
            $resourcePath = str_replace(
                '{link_id}',
                ObjectSerializer::toPathValue($linkId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation linkEdit
     *
     * Edit a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  \URLR\Model\LinkEditRequest|null $linkEditRequest Info of the link to edit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkEdit'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \URLR\Model\Link|\URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet500Response
     */
    public function linkEdit(
        string $linkId,
        ?\URLR\Model\LinkEditRequest $linkEditRequest = null,
        string $contentType = self::contentTypes['linkEdit'][0]
    ): \URLR\Model\Link|\URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet500Response
    {
        list($response) = $this->linkEditWithHttpInfo($linkId, $linkEditRequest, $contentType);
        return $response;
    }

    /**
     * Operation linkEditWithHttpInfo
     *
     * Edit a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  \URLR\Model\LinkEditRequest|null $linkEditRequest Info of the link to edit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkEdit'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \URLR\Model\Link|\URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet500Response, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function linkEditWithHttpInfo(
        string $linkId,
        ?\URLR\Model\LinkEditRequest $linkEditRequest = null,
        string $contentType = self::contentTypes['linkEdit'][0]
    ): array
    {
        $request = $this->linkEditRequest($linkId, $linkEditRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\Link',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet404Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet401Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet422Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet500Response',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\URLR\Model\Link',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\Link',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation linkEditAsync
     *
     * Edit a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  \URLR\Model\LinkEditRequest|null $linkEditRequest Info of the link to edit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkEdit'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function linkEditAsync(
        string $linkId,
        ?\URLR\Model\LinkEditRequest $linkEditRequest = null,
        string $contentType = self::contentTypes['linkEdit'][0]
    ): PromiseInterface
    {
        return $this->linkEditAsyncWithHttpInfo($linkId, $linkEditRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation linkEditAsyncWithHttpInfo
     *
     * Edit a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  \URLR\Model\LinkEditRequest|null $linkEditRequest Info of the link to edit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkEdit'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function linkEditAsyncWithHttpInfo(
        string $linkId,
        ?\URLR\Model\LinkEditRequest $linkEditRequest = null,
        string $contentType = self::contentTypes['linkEdit'][0]
    ): PromiseInterface
    {
        $returnType = '\URLR\Model\Link';
        $request = $this->linkEditRequest($linkId, $linkEditRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'linkEdit'
     *
     * @param  string $linkId Link API ID (required)
     * @param  \URLR\Model\LinkEditRequest|null $linkEditRequest Info of the link to edit (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkEdit'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function linkEditRequest(
        string $linkId,
        ?\URLR\Model\LinkEditRequest $linkEditRequest = null,
        string $contentType = self::contentTypes['linkEdit'][0]
    ): Request
    {
        // verify the required parameter 'linkId' is set
        if ($linkId === null || (is_array($linkId) && count($linkId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $linkId when calling linkEdit'
            );
        }

        $resourcePath = '/links/{link_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($linkId !== null) {
            $resourcePath = str_replace(
                '{link_id}',
                ObjectSerializer::toPathValue($linkId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($linkEditRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($linkEditRequest));
            } else {
                $httpBody = $linkEditRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new \GuzzleHttp\Psr7\MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation linkGet
     *
     * Get a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \URLR\Model\Link|\URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet500Response
     */
    public function linkGet(
        string $linkId,
        string $contentType = self::contentTypes['linkGet'][0]
    ): \URLR\Model\Link|\URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet500Response
    {
        list($response) = $this->linkGetWithHttpInfo($linkId, $contentType);
        return $response;
    }

    /**
     * Operation linkGetWithHttpInfo
     *
     * Get a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \URLR\Model\Link|\URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet500Response, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function linkGetWithHttpInfo(
        string $linkId,
        string $contentType = self::contentTypes['linkGet'][0]
    ): array
    {
        $request = $this->linkGetRequest($linkId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\Link',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet404Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet401Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet422Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet500Response',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\URLR\Model\Link',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\Link',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation linkGetAsync
     *
     * Get a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function linkGetAsync(
        string $linkId,
        string $contentType = self::contentTypes['linkGet'][0]
    ): PromiseInterface
    {
        return $this->linkGetAsyncWithHttpInfo($linkId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation linkGetAsyncWithHttpInfo
     *
     * Get a link
     *
     * @param  string $linkId Link API ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function linkGetAsyncWithHttpInfo(
        string $linkId,
        string $contentType = self::contentTypes['linkGet'][0]
    ): PromiseInterface
    {
        $returnType = '\URLR\Model\Link';
        $request = $this->linkGetRequest($linkId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'linkGet'
     *
     * @param  string $linkId Link API ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function linkGetRequest(
        string $linkId,
        string $contentType = self::contentTypes['linkGet'][0]
    ): Request
    {
        // verify the required parameter 'linkId' is set
        if ($linkId === null || (is_array($linkId) && count($linkId) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $linkId when calling linkGet'
            );
        }

        $resourcePath = '/links/{link_id}';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($linkId !== null) {
            $resourcePath = str_replace(
                '{link_id}',
                ObjectSerializer::toPathValue($linkId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation linkList
     *
     * List links
     *
     * @param  string|null $folderId Filter by Folder API ID (optional)
     * @param  string|null $tagId Filter by Tag API ID (optional)
     * @param  int|null $limit Number of items per page (optional, default to 10)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \URLR\Model\LinkList200Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet500Response
     */
    public function linkList(
        ?string $folderId = null,
        ?string $tagId = null,
        ?int $limit = 10,
        ?int $page = 1,
        string $contentType = self::contentTypes['linkList'][0]
    ): \URLR\Model\LinkList200Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet500Response
    {
        list($response) = $this->linkListWithHttpInfo($folderId, $tagId, $limit, $page, $contentType);
        return $response;
    }

    /**
     * Operation linkListWithHttpInfo
     *
     * List links
     *
     * @param  string|null $folderId Filter by Folder API ID (optional)
     * @param  string|null $tagId Filter by Tag API ID (optional)
     * @param  int|null $limit Number of items per page (optional, default to 10)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkList'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \URLR\Model\LinkList200Response|\URLR\Model\DomainGet422Response|\URLR\Model\DomainGet404Response|\URLR\Model\DomainGet401Response|\URLR\Model\DomainGet500Response, 1: int, 2: array<string, string[]>} [response data, HTTP status code, HTTP response headers]
     */
    public function linkListWithHttpInfo(
        ?string $folderId = null,
        ?string $tagId = null,
        ?int $limit = 10,
        ?int $page = 1,
        string $contentType = self::contentTypes['linkList'][0]
    ): array
    {
        $request = $this->linkListRequest($folderId, $tagId, $limit, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\LinkList200Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet422Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet404Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet401Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\URLR\Model\DomainGet500Response',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\URLR\Model\LinkList200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\LinkList200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet422Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\URLR\Model\DomainGet500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation linkListAsync
     *
     * List links
     *
     * @param  string|null $folderId Filter by Folder API ID (optional)
     * @param  string|null $tagId Filter by Tag API ID (optional)
     * @param  int|null $limit Number of items per page (optional, default to 10)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function linkListAsync(
        ?string $folderId = null,
        ?string $tagId = null,
        ?int $limit = 10,
        ?int $page = 1,
        string $contentType = self::contentTypes['linkList'][0]
    ): PromiseInterface
    {
        return $this->linkListAsyncWithHttpInfo($folderId, $tagId, $limit, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation linkListAsyncWithHttpInfo
     *
     * List links
     *
     * @param  string|null $folderId Filter by Folder API ID (optional)
     * @param  string|null $tagId Filter by Tag API ID (optional)
     * @param  int|null $limit Number of items per page (optional, default to 10)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function linkListAsyncWithHttpInfo(
        ?string $folderId = null,
        ?string $tagId = null,
        ?int $limit = 10,
        ?int $page = 1,
        string $contentType = self::contentTypes['linkList'][0]
    ): PromiseInterface
    {
        $returnType = '\URLR\Model\LinkList200Response';
        $request = $this->linkListRequest($folderId, $tagId, $limit, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'linkList'
     *
     * @param  string|null $folderId Filter by Folder API ID (optional)
     * @param  string|null $tagId Filter by Tag API ID (optional)
     * @param  int|null $limit Number of items per page (optional, default to 10)
     * @param  int|null $page Page number (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['linkList'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function linkListRequest(
        ?string $folderId = null,
        ?string $tagId = null,
        ?int $limit = 10,
        ?int $page = 1,
        string $contentType = self::contentTypes['linkList'][0]
    ): Request
    {
        if ($limit !== null && $limit > 50) {
            throw new InvalidArgumentException('invalid value for "$limit" when calling LinksApi.linkList, must be smaller than or equal to 50.');
        }
        if ($limit !== null && $limit < 1) {
            throw new InvalidArgumentException('invalid value for "$limit" when calling LinksApi.linkList, must be bigger than or equal to 1.');
        }
        if ($page !== null && $page < 1) {
            throw new InvalidArgumentException('invalid value for "$page" when calling LinksApi.linkList, must be bigger than or equal to 1.');
        }

        $resourcePath = '/links';
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $folderId,
            'folder_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tagId,
            'tag_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );


        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-KEY');
        if ($apiKey !== null) {
            $headers['X-API-KEY'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
